name: Continuous Integration
on: [push]                    # Will make the workflow run every time you push to any branch

jobs: 
  build:
    name: Build and test
    runs-on: ubuntu-latest     # Sets the build environment a machine with the latest Ubuntu installed
    steps:
    - uses: actions/checkout@v2  # Adds a step to checkout the repository code
        
    - name: Install python
      run: python -m pip install --upgrade pip setuptools wheel

    - name: Install poetry
      run: pip install poetry
    
    - name: Install flask
      run: pip install flask 

    - name: Install gunicorn
      run: poetry add gunicorn

    - name: Install pytest
      run: import pytest

    - name: Run app test
      working-directory: test_app.py
      run: test_app.py

  




