name: Continuous Integration
on: [push]                    # Will make the workflow run every time you push to any branch

jobs: 
  build:
    name: Build and test
    runs-on: ubuntu-latest     # Sets the build environment a machine with the latest Ubuntu installed
    steps:
    - uses: actions/checkout@v2  # Adds a step to checkout the repository code
    
    - name: Build Docker
      run: docker build --tag todo-app:devtest --target devtestpy .

    - name: Run Docker
      run: docker run -e API_KEY=${{ secrets.API_KEY_X }} -e API_TOKEN=${{ secrets.API_TOKEN_X }} -e TRELLO_TODO_LIST_ID =${{ secrets.TRELLO_TODO_LIST_ID_X }} -e TRELLO_DONE_LIST_ID=${{ secrets.TRELLO_DONE_LIST_ID_X}} -e TRELLO_BOARD_ID=${{ secrets.TRELLO_BOARD_ID_X}} -e FLASK_APP=${{ secrets.FLASK_APP_X}} -e FLASK_ENV=${{ secrets.FLASK_ENV_X}} -e SECRET_KEY=${{ secrets.SECRET_KEY_X }} todo-app:devtest
