name: Continuous Integration
on: 
   push:                    # Will make the workflow run every time you push to any branch
    paths-ignore:
    - '**/README.md'
   pull_request:
    paths-ignore:
    - '**/README.md'

jobs:
  job-one:
    name: Build and test
    runs-on: ubuntu-latest     # Sets the build environment a machine with the latest Ubuntu installed
    steps:
    - uses: actions/checkout@v2  # Adds a step to checkout the repository code
    
    - name: Build Docker
      run: docker build --tag todo-app:devtest --target devtestpy .

    - name: Run Docker
      run: docker run -e FLASK_APP=${{ secrets.FLASK_APP_X}} -e FLASK_ENV=${{ secrets.FLASK_ENV_X}} -e SECRET_KEY=${{ secrets.SECRET_KEY_X }} todo-app:devtest

  job-two:
    name: image push
    runs-on: ubuntu-latest
    needs: job-one
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      -
          name: Login to DockerHub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_TOKEN }}
      -
          name: Build
          run: docker build -t prodpy --tag prod_image .
      - 
          name: Push
          run: docker push prod_image 